build: 
	@npm run build

build-docker:
	@docker build -t newsletter-sign-up-form ./

run:
	@docker run -p 3000:3000 -d newsletter-sign-up-form

setup:
	@npm i 

test-run:
	@npm run cypress:run

test-open:
	@npm run cypress:open